<?php

namespace Database\Seeders;

use App\Models\DriverProfile;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class HireDriverSeeder extends Seeder
{
    public function run(): void
    {
        $drivers = [
            // ==================== GHANA (GHA) ====================
            [
                'name' => 'Kwame Mensah',
                'email' => 'kwame.driver@ridemycars.com',
                'phone' => '+233241234567',
                'country' => 'GHA',
                'service_area' => 'Accra, Airport City & Tema',
                'license' => 'DL-GH-441209',
                'hourly_rate' => 65.00,
                'daily_rate' => 450.00,
                'weekly_rate' => 2700.00,
                'experience' => 8,
                'rating' => 4.95,
                'total_trips' => 142,
                'bio' => 'Executive chauffeur with 8+ years of private driving experience. Specialized in airport pick-ups, corporate client logistics, and luxury sedan handling across Greater Accra.',
                'image_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Kofi Boateng',
                'email' => 'kofi.boateng@ridemycars.com',
                'phone' => '+233249876543',
                'country' => 'GHA',
                'service_area' => 'Accra, Cantonments & East Legon',
                'license' => 'DL-GH-552310',
                'hourly_rate' => 80.00,
                'daily_rate' => 550.00,
                'weekly_rate' => 3200.00,
                'experience' => 11,
                'rating' => 4.98,
                'total_trips' => 215,
                'bio' => 'Senior executive chauffeur and VIP escort specialist. Former embassy driver with extensive knowledge of VIP security protocols, diplomatic routes, and luxury European vehicles.',
                'image_url' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Emmanuel Addo',
                'email' => 'emmanuel.addo@ridemycars.com',
                'phone' => '+233243322110',
                'country' => 'GHA',
                'service_area' => 'Accra, Osu, Ridge & Dzorwulu',
                'license' => 'DL-GH-663421',
                'hourly_rate' => 55.00,
                'daily_rate' => 380.00,
                'weekly_rate' => 2300.00,
                'experience' => 6,
                'rating' => 4.90,
                'total_trips' => 98,
                'bio' => 'Professional and courteous private chauffeur. Excellent route navigator, fluent in English and Twi, available for full-day corporate assignments and family city excursions.',
                'image_url' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Nana Yaw Osei',
                'email' => 'nana.osei@ridemycars.com',
                'phone' => '+233245566778',
                'country' => 'GHA',
                'service_area' => 'Greater Accra & Kumasi Inter-City',
                'license' => 'DL-GH-774532',
                'hourly_rate' => 70.00,
                'daily_rate' => 480.00,
                'weekly_rate' => 2900.00,
                'experience' => 9,
                'rating' => 4.92,
                'total_trips' => 164,
                'bio' => 'Experienced inter-city and long-distance private driver. Expert in cross-regional transit between Accra, Kumasi, Cape Coast, and Takoradi with an immaculate safety record.',
                'image_url' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Abena Serwaa',
                'email' => 'abena.serwaa@ridemycars.com',
                'phone' => '+233246677889',
                'country' => 'GHA',
                'service_area' => 'Accra, Labone, Roman Ridge & Airport',
                'license' => 'DL-GH-885643',
                'hourly_rate' => 75.00,
                'daily_rate' => 500.00,
                'weekly_rate' => 3000.00,
                'experience' => 7,
                'rating' => 5.00,
                'total_trips' => 112,
                'bio' => 'Top-rated executive female chauffeur catering to diplomats, business leaders, and family VIP travel. Certified defensive driver prioritizing comfort, privacy, and precision timing.',
                'image_url' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Samuel Tetteh',
                'email' => 'samuel.tetteh@ridemycars.com',
                'phone' => '+233247788990',
                'country' => 'GHA',
                'service_area' => 'Tema Harbour, Spintex & Industrial Area',
                'license' => 'DL-GH-996754',
                'hourly_rate' => 60.00,
                'daily_rate' => 420.00,
                'weekly_rate' => 2500.00,
                'experience' => 10,
                'rating' => 4.88,
                'total_trips' => 180,
                'bio' => 'Commercial fleet & executive van driver. Seasoned expert in executive passenger transport, port logistics shuttles, and group transportation for corporate conferences.',
                'image_url' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Richmond Mensah',
                'email' => 'richmond.mensah@ridemycars.com',
                'phone' => '+233248899001',
                'country' => 'GHA',
                'service_area' => 'Accra, Achimota & West Legon',
                'license' => 'DL-GH-117865',
                'hourly_rate' => 68.00,
                'daily_rate' => 460.00,
                'weekly_rate' => 2800.00,
                'experience' => 8,
                'rating' => 4.94,
                'total_trips' => 135,
                'bio' => 'Specialized in luxury executive transport and wedding motorcade driving. Calm under pressure with comprehensive knowledge of all bypasses avoiding city traffic bottlenecks.',
                'image_url' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
            ],

            // ==================== UNITED STATES (USA) ====================
            [
                'name' => 'Michael Chen',
                'email' => 'michael@example.com',
                'phone' => '+12125550143',
                'country' => 'USA',
                'service_area' => 'New York Metro, Manhattan & Westchester',
                'license' => 'DL-US-12345',
                'hourly_rate' => 38.00,
                'daily_rate' => 260.00,
                'weekly_rate' => 1500.00,
                'experience' => 10,
                'rating' => 4.95,
                'total_trips' => 195,
                'bio' => 'Premier private chauffeur with a decade of high-end sedan and SUV experience in Manhattan. Trusted by corporate executives and VIP visitors.',
                'image_url' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah@example.com',
                'phone' => '+12125550188',
                'country' => 'USA',
                'service_area' => 'New York, NJ & Long Island',
                'license' => 'DL-US-67890',
                'hourly_rate' => 32.00,
                'daily_rate' => 220.00,
                'weekly_rate' => 1300.00,
                'experience' => 7,
                'rating' => 4.90,
                'total_trips' => 148,
                'bio' => 'Punctual, friendly, and discreet private driver. Ideal for family trips, executive airport transfers (JFK/LGA/EWR), and private day bookings.',
                'image_url' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'David Rodriguez',
                'email' => 'david@example.com',
                'phone' => '+13105550192',
                'country' => 'USA',
                'service_area' => 'Los Angeles, Beverly Hills & Orange County',
                'license' => 'DL-US-11223',
                'hourly_rate' => 45.00,
                'daily_rate' => 300.00,
                'weekly_rate' => 1800.00,
                'experience' => 9,
                'rating' => 5.00,
                'total_trips' => 220,
                'bio' => 'Bilingual executive chauffeur (English/Spanish). Extensive experience driving exotic and ultra-luxury vehicles for studio executives, celebrities, and business delegations.',
                'image_url' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Emily Thompson',
                'email' => 'emily@example.com',
                'phone' => '+13125550174',
                'country' => 'USA',
                'service_area' => 'Chicago Metro & North Shore',
                'license' => 'DL-US-44556',
                'hourly_rate' => 30.00,
                'daily_rate' => 210.00,
                'weekly_rate' => 1250.00,
                'experience' => 6,
                'rating' => 4.88,
                'total_trips' => 105,
                'bio' => 'Safe, patient, and detail-oriented private chauffeur. Specializes in executive travel, business dinners, and winter weather defensive driving.',
                'image_url' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Marcus Washington',
                'email' => 'marcus.washington@ridemycars.com',
                'phone' => '+14045550165',
                'country' => 'USA',
                'service_area' => 'Atlanta, Buckhead & Midtown',
                'license' => 'DL-US-55667',
                'hourly_rate' => 42.00,
                'daily_rate' => 280.00,
                'weekly_rate' => 1650.00,
                'experience' => 12,
                'rating' => 4.97,
                'total_trips' => 175,
                'bio' => 'Former private security detail driver. Exceptional defensive driving skills, discreet, and reliable for high-profile business clients and VIP airport services.',
                'image_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'James Wilson',
                'email' => 'james@example.com',
                'phone' => '+13055550129',
                'country' => 'USA',
                'service_area' => 'Miami, Fort Lauderdale & Palm Beach',
                'license' => 'DL-US-77889',
                'hourly_rate' => 40.00,
                'daily_rate' => 270.00,
                'weekly_rate' => 1600.00,
                'experience' => 9,
                'rating' => 4.92,
                'total_trips' => 138,
                'bio' => 'South Florida private chauffeur specializing in luxury SUVs, coastal travel, and evening event chauffeuring with top-tier hospitality.',
                'image_url' => 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
            ],

            // ==================== NIGERIA (NGA) ====================
            [
                'name' => 'Emeka Okafor',
                'email' => 'emeka.driver@ridemycars.com',
                'phone' => '+2348031234567',
                'country' => 'NGA',
                'service_area' => 'Lagos Island, Victoria Island & Lekki',
                'license' => 'DL-NG-778123',
                'hourly_rate' => 6500.00,
                'daily_rate' => 45000.00,
                'weekly_rate' => 250000.00,
                'experience' => 8,
                'rating' => 4.95,
                'total_trips' => 195,
                'bio' => 'Top rated executive driver in Lagos. Deep knowledge of island & mainland routes, seasoned in corporate transit, airport transfers, and executive security.',
                'image_url' => 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Adebayo Adeleke',
                'email' => 'adebayo.driver@ridemycars.com',
                'phone' => '+2348059876543',
                'country' => 'NGA',
                'service_area' => 'Abuja, Central Business District & Maitama',
                'license' => 'DL-NG-889234',
                'hourly_rate' => 7000.00,
                'daily_rate' => 48000.00,
                'weekly_rate' => 270000.00,
                'experience' => 10,
                'rating' => 4.92,
                'total_trips' => 160,
                'bio' => 'Corporate and diplomatic chauffeur based in Abuja. Experienced with government officials, international delegates, and high-security convoys.',
                'image_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Chinedu Eze',
                'email' => 'chinedu.driver@ridemycars.com',
                'phone' => '+2348071122334',
                'country' => 'NGA',
                'service_area' => 'Lagos, Ikeja Airport & Mainland',
                'license' => 'DL-NG-990345',
                'hourly_rate' => 5500.00,
                'daily_rate' => 38000.00,
                'weekly_rate' => 220000.00,
                'experience' => 6,
                'rating' => 4.88,
                'total_trips' => 110,
                'bio' => 'Reliable and courteous private driver specializing in Murtala Muhammed Airport shuttles, business meetings, and inter-city trips to Ibadan.',
                'image_url' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
            ],

            // ==================== SOUTH AFRICA (ZAF) ====================
            [
                'name' => 'Sipho Ndlovu',
                'email' => 'sipho.driver@ridemycars.com',
                'phone' => '+27821234567',
                'country' => 'ZAF',
                'service_area' => 'Johannesburg, Sandton & Rosebank',
                'license' => 'DL-ZA-339182',
                'hourly_rate' => 280.00,
                'daily_rate' => 1900.00,
                'weekly_rate' => 11000.00,
                'experience' => 8,
                'rating' => 4.95,
                'total_trips' => 175,
                'bio' => 'Reliable Sandton and Johannesburg private chauffeur. Experienced with corporate executives, airport transfers, and luxury commercial transport.',
                'image_url' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Johan Van der Merwe',
                'email' => 'johan.driver@ridemycars.com',
                'phone' => '+27839876543',
                'country' => 'ZAF',
                'service_area' => 'Cape Town, Atlantic Seaboard & Winelands',
                'license' => 'DL-ZA-440293',
                'hourly_rate' => 320.00,
                'daily_rate' => 2200.00,
                'weekly_rate' => 13000.00,
                'experience' => 11,
                'rating' => 4.98,
                'total_trips' => 220,
                'bio' => 'Premier Western Cape private chauffeur. Extensive experience with wine tour excursions, executive airport transfers, and luxury coastal sightseeing.',
                'image_url' => 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
            ],
            [
                'name' => 'Thabo Molefe',
                'email' => 'thabo.driver@ridemycars.com',
                'phone' => '+27841122334',
                'country' => 'ZAF',
                'service_area' => 'Pretoria, Centurion & OR Tambo Airport',
                'license' => 'DL-ZA-551304',
                'hourly_rate' => 260.00,
                'daily_rate' => 1750.00,
                'weekly_rate' => 10000.00,
                'experience' => 7,
                'rating' => 4.89,
                'total_trips' => 130,
                'bio' => 'Professional Pretoria executive driver specializing in embassy transport, government delegations, and OR Tambo international airport connections.',
                'image_url' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
            ],
        ];

        foreach ($drivers as $data) {
            $user = User::updateOrCreate(
                ['email' => $data['email']],
                [
                    'name' => $data['name'],
                    'password' => Hash::make('123456'),
                    'role' => 'driver',
                    'phone' => $data['phone'] ?? null,
                    'account_status' => 'active',
                    'email_verified_at' => now(),
                ]
            );

            DriverProfile::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'license_number' => $data['license'],
                    'hourly_rate' => $data['hourly_rate'],
                    'daily_rate' => $data['daily_rate'],
                    'weekly_rate' => $data['weekly_rate'],
                    'experience_years' => $data['experience'],
                    'country' => $data['country'],
                    'service_area' => $data['service_area'],
                    'is_available' => true,
                    'rating' => $data['rating'],
                    'total_trips' => $data['total_trips'],
                    'verification_status' => 'verified',
                    'image_url' => $data['image_url'],
                    'bio' => $data['bio'],
                    'last_location_update' => now(),
                ]
            );
        }

        // Also normalize any old records where country was 'Ghana' to 'GHA'
        DriverProfile::where('country', 'Ghana')->update(['country' => 'GHA']);
        DriverProfile::where('country', 'United States')->update(['country' => 'USA']);
        DriverProfile::where('country', 'Nigeria')->update(['country' => 'NGA']);
        DriverProfile::where('country', 'South Africa')->update(['country' => 'ZAF']);
    }
}
