<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use App\Models\Ride;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        // Mark old test rental bookings as completed so vehicles are immediately available
        Ride::whereNotNull('vehicle_id')
            ->whereIn('status', ['confirmed', 'accepted', 'in_progress'])
            ->update(['status' => 'completed']);

        $vehicles = [
            [
                'make' => 'Tesla',
                'model' => 'Model S Plaid',
                'year' => '2024',
                'license_plate' => 'TSL-9901',
                'category' => 'Luxury',
                'type' => 'Sedan',
                'daily_rate' => 180.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'seats' => 5,
                'luggage' => 3,
                'doors' => 4,
                'min_driver_age' => 18,
                'security_deposit_amount' => 500.00,
                'daily_mileage_limit' => 300,
                'image_url' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'BMW',
                'model' => 'M4 Competition',
                'year' => '2024',
                'license_plate' => 'BMW-4001',
                'category' => 'Luxury',
                'type' => 'Coupe',
                'daily_rate' => 165.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 4,
                'luggage' => 2,
                'doors' => 2,
                'min_driver_age' => 18,
                'security_deposit_amount' => 500.00,
                'daily_mileage_limit' => 250,
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Land Rover',
                'model' => 'Range Rover Sport',
                'year' => '2024',
                'license_plate' => 'RNG-7007',
                'category' => 'SUV',
                'type' => 'SUV',
                'daily_rate' => 155.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'luggage' => 4,
                'doors' => 5,
                'min_driver_age' => 18,
                'security_deposit_amount' => 400.00,
                'daily_mileage_limit' => 250,
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'S-Class S580',
                'year' => '2024',
                'license_plate' => 'MBZ-5800',
                'category' => 'Luxury',
                'type' => 'Sedan',
                'daily_rate' => 195.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'luggage' => 3,
                'doors' => 4,
                'min_driver_age' => 18,
                'security_deposit_amount' => 600.00,
                'daily_mileage_limit' => 300,
                'image_url' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Porsche',
                'model' => '911 Carrera Cabriolet',
                'year' => '2024',
                'license_plate' => 'POR-9110',
                'category' => 'Luxury',
                'type' => 'Convertible',
                'daily_rate' => 250.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 4,
                'luggage' => 2,
                'doors' => 2,
                'min_driver_age' => 21,
                'security_deposit_amount' => 800.00,
                'daily_mileage_limit' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Audi',
                'model' => 'Q8 e-tron',
                'year' => '2024',
                'license_plate' => 'AUD-8800',
                'category' => 'SUV',
                'type' => 'SUV',
                'daily_rate' => 135.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'seats' => 5,
                'luggage' => 4,
                'doors' => 5,
                'min_driver_age' => 18,
                'security_deposit_amount' => 350.00,
                'daily_mileage_limit' => 300,
                'image_url' => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Toyota',
                'model' => 'Camry Hybrid XSE',
                'year' => '2024',
                'license_plate' => 'TOY-2024',
                'category' => 'Sedan',
                'type' => 'Midsize',
                'daily_rate' => 55.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'luggage' => 3,
                'doors' => 4,
                'min_driver_age' => 18,
                'security_deposit_amount' => 200.00,
                'daily_mileage_limit' => 400,
                'image_url' => 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Honda',
                'model' => 'Civic Touring',
                'year' => '2024',
                'license_plate' => 'HND-5500',
                'category' => 'Compact',
                'type' => 'Compact',
                'daily_rate' => 45.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'luggage' => 2,
                'doors' => 4,
                'min_driver_age' => 18,
                'security_deposit_amount' => 150.00,
                'daily_mileage_limit' => 350,
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Ford',
                'model' => 'Mustang GT V8',
                'year' => '2024',
                'license_plate' => 'FRD-5000',
                'category' => 'Luxury',
                'type' => 'Convertible',
                'daily_rate' => 110.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 4,
                'luggage' => 2,
                'doors' => 2,
                'min_driver_age' => 21,
                'security_deposit_amount' => 350.00,
                'daily_mileage_limit' => 250,
                'image_url' => 'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Cadillac',
                'model' => 'Escalade ESV',
                'year' => '2024',
                'license_plate' => 'CAD-9900',
                'category' => 'SUV',
                'type' => 'SUV',
                'daily_rate' => 185.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 7,
                'luggage' => 6,
                'doors' => 5,
                'min_driver_age' => 21,
                'security_deposit_amount' => 500.00,
                'daily_mileage_limit' => 300,
                'image_url' => 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Hyundai',
                'model' => 'Tucson Hybrid',
                'year' => '2024',
                'license_plate' => 'HYU-7700',
                'category' => 'SUV',
                'type' => 'SUV',
                'daily_rate' => 65.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'luggage' => 3,
                'doors' => 5,
                'min_driver_age' => 18,
                'security_deposit_amount' => 200.00,
                'daily_mileage_limit' => 350,
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'Sprinter Luxury Van',
                'year' => '2023',
                'license_plate' => 'VAN-8800',
                'category' => 'Van',
                'type' => 'Van',
                'daily_rate' => 140.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 12,
                'luggage' => 8,
                'doors' => 4,
                'min_driver_age' => 21,
                'security_deposit_amount' => 400.00,
                'daily_mileage_limit' => 300,
                'image_url' => 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Toyota',
                'model' => 'RAV4 Hybrid AWD',
                'year' => '2024',
                'license_plate' => 'TOY-4400',
                'category' => 'SUV',
                'type' => 'SUV',
                'daily_rate' => 70.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'luggage' => 3,
                'doors' => 5,
                'min_driver_age' => 18,
                'security_deposit_amount' => 200.00,
                'daily_mileage_limit' => 350,
                'image_url' => 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Corvette Stingray',
                'year' => '2024',
                'license_plate' => 'VET-3300',
                'category' => 'Luxury',
                'type' => 'Sports',
                'daily_rate' => 220.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 2,
                'luggage' => 1,
                'doors' => 2,
                'min_driver_age' => 25,
                'security_deposit_amount' => 700.00,
                'daily_mileage_limit' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Golf GTI',
                'year' => '2023',
                'license_plate' => 'GTI-2000',
                'category' => 'Compact',
                'type' => 'Hatchback',
                'daily_rate' => 50.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'luggage' => 2,
                'doors' => 4,
                'min_driver_age' => 18,
                'security_deposit_amount' => 150.00,
                'daily_mileage_limit' => 300,
                'image_url' => 'https://images.unsplash.com/photo-1471440671318-55bdbb772f93?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
            [
                'make' => 'Nissan',
                'model' => 'Versa Note',
                'year' => '2023',
                'license_plate' => 'ECO-1000',
                'category' => 'Economy',
                'type' => 'Economy',
                'daily_rate' => 30.00,
                'is_available' => true,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'luggage' => 2,
                'doors' => 4,
                'min_driver_age' => 18,
                'security_deposit_amount' => 100.00,
                'daily_mileage_limit' => 400,
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
                'approval_status' => 'approved',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::updateOrCreate(['license_plate' => $vehicle['license_plate']], $vehicle);
        }
    }
}
